name: slide_show_pro
description: "Slide Show Pro is a powerful Flutter package 
designed to simplify the creation of animated sliders. 
With Slide Show Pro, you can seamlessly integrate various 
animation effects such as fade, scale, slide, and rotate 
into your projects. It also supports the ability to mix 
and match these effects to create stunning and dynamic 
transitions.

Whether you're building an image gallery, 
a product showcase, or any feature that requires 
smooth and engaging animations, Slide Show Pro makes 
it easy to achieve professional-grade results with 
minimal effort."

version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

